/** Model: Book. */
export type Book = Readonly<{

    /** Book name. */
    name: string;

    /** Book authors. */
    authors: string;

    /** Book publication year. */
    publicationYear: number | null;

    /** Book rating. */
    rating: number | null;

    /** Book ISBN. */
    ISBN: string | null;

    /** Book cover. */
    cover: string | null;

    /** Book uid (generated by firestore). */
    uid: string;
}>